$Type: Settings$ProjectSettings
Settings:
    - $Type: Forms$WebUIProjectSettingsPart
      EnableMicroflowReachabilityAnalysis: true
      EnableNewWidgetGeneration: true
      EnableWidgetBundling: false
      ThemeModuleOrder: []
      UrlPrefix: p
      UseOptimizedClient: "No"
    - $Type: Settings$IntegrationProjectSettingsPart
    - $Type: Settings$ConfigurationSettings
      Configurations:
        - $Type: Settings$ServerConfiguration
          ApplicationRootUrl: http://localhost:8080/
          ConstantValues: []
          CustomSettings: []
          DatabaseName: default
          DatabasePassword: ""
          DatabaseType: Hsqldb
          DatabaseUrl: ""
          DatabaseUseIntegratedSecurity: false
          DatabaseUserName: ""
          ExtraJvmParameters: ""
          HttpPortNumber: 8080
          MaxJavaHeapSize: 0
          Name: Default
          OpenAdminPort: true
          OpenHttpPort: false
          ServerPortNumber: 8090
    - $Type: Settings$ModelSettings
      AfterStartupMicroflow: ""
      AllowUserMultipleSessions: true
      BcryptCost: 12
      BeforeShutdownMicroflow: ""
      DefaultTimeZoneCode: ""
      EnableDataStorageOptimisticLocking: false
      FirstDayOfWeek: Default
      HashAlgorithm: BCrypt
      HealthCheckMicroflow: ""
      JavaVersion: Java11
      RoundingMode: HalfUp
      ScheduledEventTimeZoneCode: Etc/UTC
      UseDatabaseForeignKeyConstraints: true
      UseOQLVersion2: false
      UseSystemContextForBackgroundTasks: false
    - $Type: Settings$ConventionSettings
      ActionActivityDefaultColors: []
      DefaultSequenceFlowLineType: BezierCurve
      LowerCaseMicroflowVariables: false
    - $Type: Settings$LanguageSettings
      DefaultLanguageCode: en_US
      Languages:
        - $Type: Texts$Language
          CheckCompleteness: false
          Code: en_US
          CustomDateFormat: ""
          CustomDateTimeFormat: ""
          CustomTimeFormat: ""
    - $Type: Settings$CertificateSettings
      Certificates: []
    - $Type: Settings$WorkflowsProjectSettingsPart
      DefaultTaskParallelism: 3
      OnWorkflowEvent: []
      UserEntity: System.User
      UsertaskOnStateChangeEvent: null
      WorkflowEngineParallelism: 5
      WorkflowOnStateChangeEvent: null
    - $Type: Settings$JarDeploymentSettings
      Exclusions: []
    - $Type: Settings$DistributionSettings
      BasedOnVersion: ""
      IsDistributable: false
      Version: ""
